### ISSUE TITLE
Code readability

### ISSUE THREAD

**Issue by jby1993** [nv-tlabs/nglod#10]
Hi, thanks for releasing the excellent work. I want to figure out the real-time rendering, but I found there are no hints for helping me understand the code, and the paper also lacks discussions on implementation details. For example, what is SPC, and how it's worked? I want to know if there is some reference document? Thanks again.

**Comment by tovacinni** [comment]
Thanks for you interest in our paper.

It's hard to help without knowing where you specifically have confusions, but the "raytracing" part of the code follows the same function names discussed in the paper. The tensors used in the raytracing (like the octree, points, etc) are also described in the paper. 

We'll probably release a new version soon which includes PyBind11 bindings for the existing code, which may make some parts of the code easier to parse. Until then, I'm happy to answer any specific questions you might have.

**Comment by joeylitalien** [comment]
Hi @jby1993, 

Please have a look at the most recent docs for Kaolin, which now include a [discussion on structured point clouds (SPC)](https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.spc.html). Along with the recent refactor, it should provide more information on how we implemented the sparse octree for NGLOD.
