### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by sixftninja** [nv-tlabs/nglod#27]
Any advice on how to get nglod running on NVIDIA Ampere GPUs? I tried to install and run on a Ubuntu 20.04, CUDA 11.5, A4000 16 GB system but it doesn't work.
I don't think PyTorch 1.6 supports Ampere. Would it matter if I installed another version of pytroch?

**Comment by joeylitalien** [comment]
Hi @sixftninja,

AFAIK our codebase has not been tested on this architecture with CUDA 11.4+. Have you tried upgrading your PyTorch to the latest version 1.11? I don't think there's anything that prohibits this in the code. If that doesn't work, please include your error message so we can better assess the problem.

Best,
Joey

**Comment by sixftninja** [comment]
Hi Joey,

Thanks for your reply. Upgrading to latest PyTorch helped. Since I installed PyTorch via Conda (Cuda 11.3); I could not test on CUDA 11.5.
