### ISSUE TITLE
Modeling multiple shapes & differentiable renderer

### ISSUE THREAD

**Issue by hakanyi** [nv-tlabs/nglod#3]
Thank you for this great work and the well-written paper and congrats on the talk! 

I have two questions I was hoping you could clarify:

1. I understand that your experiments consist of overfitting individual shapes. Have you tried modeling multiple shapes by means of an extension of or alternative to this idea (that is featured prominently in DeepSDF):
_"An optional input “shape” feature vector z∈Rm can be used to condition the network to fit different shapes with a fixed θ"_

2. You write _"As such, we can leverage the same techniques proposed in these works to make our renderer also differentiable."_ Does that mean that this is possible future work or is it already implemented? I might have missed it in the paper, sorry if that's the case! 

Thanks a lot in advance!

**Comment by tovacinni** [comment]
1. We have, and you could consider the "generalization" experiment in the paper to be one form of this but with a variable size latent code.

2. This is more on the line of possible future work, but the code implemented as is can be used as a differentiable renderer.

**Comment by hakanyi** [comment]
Much appreciated, @tovacinni!

Can you kindly elaborate on 1.? My understanding of the "generalization" experiment under 4.3 is that you overfit sparse features + MLP weights to individual shapes before fixing the MLP weights and, again, overfitting sparse features to a second shape. Is my understanding correct? What I wonder here is whether one could "sample" shapes from nglod just as one can using DeepSDF (coming down to sampling from a mutivariate Gaussian) after training on a shape repository instead of an individual shape.
