### ISSUE TITLE
ModuleNotFoundError: No module named 'sol_nglod'

### ISSUE THREAD

**Issue by zhaoyuanyuan2011** [nv-tlabs/nglod#30]
When I'm trying to train or render, I get:

Traceback (most recent call last):
  File "app/main.py", line 32, in <module>
    from lib.trainer import Trainer
  File "/usr/nglod/sdf-net/lib/trainer.py", line 47, in <module>
    from lib.models import *
  File "/usr/nglod/sdf-net/lib/models/__init__.py", line 25, in <module>
    from .SOL_NGLOD import SOL_NGLOD
  File "/usr/nglod/sdf-net/lib/models/SOL_NGLOD.py", line 25, in <module>
    import sol_nglod
ModuleNotFoundError: No module named 'sol_nglod'

There is indeed a `sol_nglod` dir in `/sdf-net/lib/extensions/`, and everything went well before this. I'm using a python 3.7 virtualenv because conda env always has gcc-5 issues when installing pyexr. Does anyone have idea about this? Thanks!

**Comment by mckay-w** [comment]
how do you fix it?

**Comment by joeylitalien** [comment]
Hi @mckay-w,

You need to build the CUDA extensions. See the [instructions](https://github.com/nv-tlabs/nglod?tab=readme-ov-file#building-cuda-extensions).

**Comment by mckay-w** [comment]
> Hi @mckay-w,
> 
> You need to build the CUDA extensions. See the [instructions](https://github.com/nv-tlabs/nglod?tab=readme-ov-file#building-cuda-extensions).

tks， I fixed it
