### ISSUE TITLE
abbreviation problem

### ISSUE THREAD

**Issue by dhuwzj** [nv-tlabs/nglod#34]
what is sol？(like sol-renderer)
Are there any notes on abbreviations?

**Comment by joeylitalien** [comment]
SOL is short for _Speed of Light_ and it's an internal abbreviation used by NVIDIA. IIRC, it's essentially the mindset of learning, acting and moving super fast with extreme performance, something NVIDIA strives for. In our case, `sol-renderer` was the final form of our real-time renderer before we released the paper.
