### ISSUE TITLE
ShapeNet150 data

### ISSUE THREAD

**Issue by GavinGuan95** [nv-tlabs/nglod#41]
Great work! I am wondering for the shapenet150 data, the airplane, car and chair categories are used. But how did you select the 50 models within each category?

**Comment by joeylitalien** [comment]
Hi @GavinGuan95,

As far as I can remember, they were chosen uniformly at random. I don't think we manually picked them, although it is possible we discarded some shapes if we thought they were too simple upon inspection.

Hope this helps,
Joey

**Comment by joeylitalien** [comment]
I will close this issue for now, but feel free to reopen if you have more questions regarding ShapeNet150.
