### ISSUE TITLE
Path to pretrained model weights.

### ISSUE THREAD

**Issue by helenacorreia** [nv-tlabs/nglod#8]
Hello everyone! I have a question about the model to train. Before testing the code is it necessary to train??

**Comment by joeylitalien** [comment]
We don't provide pre-trained models, so you will have to train a base shape from scratch. Instructions on how to optimize from an OBJ mesh (e.g., Armadillo) can be found [here](https://github.com/nv-tlabs/nglod#training--rendering).

**Comment by harora** [comment]
Can you share the code used to generate armadillo_normalized.obj?

**Comment by tovacinni** [comment]
@harora armadillo_normalized.obj will be automatically generated by the code if you follow the example command
